### ISSUE TITLE
mqtt: combine two registers

### ISSUE THREAD

**Issue by pohly** [bohdan-s/SunGather#139]
I have a SunGrow SG15RT with two strings attached. I would like to see the power generated by each string in HomeAssistant, because a) I am curious :grin: and b) that would allow me to configure the forecast differently for each part of my roof.

I could export `mppt_1_voltage/mppt_2_voltage/mppt_1_current/mppt_2_current` separately and multiple voltage with current in a HomeAssistant helper to get power, but that seems wasteful. Would it be possible to do the transformation directly in SunGather? Something like this:

```
  - name: mqtt
    topic: "solar/main"
    ...
    homeassistant: True
    ha_sensors:
      - name: "west"
        sensor_type: sensor
        dev_class: power
        state_class: measurement
        icon: "mdi:solar-panel-large"
        value_template: "{{ value_json.mppt_1_voltage * value_json.mppt_1_current | round(2) }}"

      - name: "east"
        sensor_type: sensor
        dev_class: power
        state_class: measurement
        icon: "mdi:solar-panel"
        value_template: "{{ value_json.mppt_2_voltage * value_json.mppt_2_current | round(2) }}"
```

I haven't tried it yet (don't want to disturb current measurements) but I don't expect it to work anyway because there is no `register(s)` field.
