### ISSUE TITLE
Home Assistant sensor setup and Energy platform

### ISSUE THREAD

**Issue by rark-ha** [bohdan-s/SunGather#4]
Following on from the comment in the closed item https://github.com/bohdan-s/SunGather/issues/2#issuecomment-999236995

@bohdan-s the updates you've made in the past 48 hrs have fixed my initial issue as HA now generates 6 sensors. For others that would like a walk-through doc please read below.

In the SunGather config.yaml you need to set the smart_meter if you have one;
```
smart_meter: True
```

HA sensors created by the MQTT auto-discovery;

```
sensor.inverter_active_power
sensor.inverter_daily_generation
sensor.inverter_export_to_grid
sensor.inverter_import_from_grid
sensor.inverter_load_power
sensor.inverter_meter_power
```

Used the README settings for HA sensors and put the following into your sensors.yaml

```
sensor:
  - platform: integration
    source: sensor.inverter_active_power
  - platform: integration
    source: sensor.inverter_export_to_grid
  - platform: integration
    source: sensor.inverter_import_from_grid
```

The additional sensors then setup in HA are the following with Wh unit of measurement for the Energy platform.

```
sensor.sensor_inverter_active_power_integral
sensor.sensor_inverter_export_to_grid_integral
sensor.sensor_inverter_import_from_grid_integral
```

You need to utilise the customize.yaml manual method to get some friendly names and icons. Add the following;

```
sensor.sensor_inverter_active_power_integral:
  icon: mdi:solar-power
  friendly_name: Solar Generation
sensor.sensor_inverter_export_to_grid_integral:
  icon: mdi:transmission-tower-export
  friendly_name: Grid Export
sensor.sensor_inverter_import_from_grid_integral:
  icon: mdi:transmission-tower-import
  friendly_name: Grid Import
```

Navigate to the Energy platform (Configuration > Energy). Add these sensors to the following areas:

```
Electricity Grid > Grid Import - sensor.sensor_inverter_import_from_grid_integral
Electricity Grid > Grid Export - sensor.sensor_inverter_export_to_grid_integral
Solar Panels > Solar Production - sensor.sensor_inverter_active_power_integral
```
